spring.datasource.url=jdbc:mysql://localhost:3306/spendwise
spring.datasource.username=root
spring.datasource.password=system

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
jwt.secret=MyVeryStrongSecretKeyForSpendWiseProject123456789
jwt.expiration=86400000